// Generated by CoffeeScript 1.6.3
(function() {
  describe('TemplateManager', function() {
    return describe('retrieveTemplate', function() {
      context('correctly formed HTML element', function() {
        return it('retrieves a mustache template', function() {
          return expect(App.Templates.mustacheTemplate.innerHTML).to.contain('<p class=\'listening-to\'>My current jam:</p>');
        });
      });
      return context('incorrectly formed HTML element', function() {
        return context('no templateurl', function() {
          beforeEach(function() {
            var div;
            div = document.getElementById('thisismyjam');
            return delete div.dataset.templateUrl;
          });
          return it('throws an error', function() {
            return expect(function() {
              return App.templateManager.retrieveTemplate();
            }).to["throw"](App.Errors.noTemplateUrl);
          });
        });
      });
    });
  });

  describe('Jam', function() {
    return describe('initRequest', function() {
      return context('no username', function() {
        beforeEach(function() {
          var div;
          div = document.getElementById('thisismyjam');
          return delete div.dataset.tmjUsername;
        });
        return it('throws an error', function() {
          return expect(function() {
            return App.jam.initRequest();
          }).to["throw"](App.Errors.noUsername);
        });
      });
    });
  });

}).call(this);
